### ISSUE TITLE
Cluster Management: Cluster registration workflow design

### ISSUE THREAD

**Issue by ffforest** [KusionStack/karpor#54]
### What would you like to be added?

Currently Karbour registers/updates/deletes new cluster by installing a CR that looks like this in the Karbour apiserver:
```
apiVersion: cluster.karbour.com/v1beta1
kind: Cluster
metadata:
  name: [local-cluster-nickname]
spec:
  provider: [local-cluster-provider] #optional
  access:
    endpoint: [local-cluster-endpoint]
    caBundle: [local-cluster-CABundle]
    credential:
      type: ServiceAccountToken #SAToken or x509
      serviceAccountToken: [local-cluster-credential]
```
This is a very manual process. The ability to register/update/delete clusters should be exposed to the end user with a recommended workflow.

### Why is this needed?

User should be able to register new cluster via a consistent workflow without having to install Custom Resources manually.
