### ISSUE TITLE
Governance: Automatically update the appVersion in Chart when released

### ISSUE THREAD

**Issue by elliotxx** [KusionStack/karpor#547]
### What would you like to be added?

Automatically update the appVersion in Chart when released.

### Why is this needed?

The current release process is:
1. Push tag, such as `v0.4.5`
2. Auto trigger a karpor release pipeline. It will build an image and publish changelog, artifacts to the github release.
3. Modify Karpor Chart's `appVersion` to the new version, such as `v0.4.5`.
4. Auto trigger a chart release pipeline. 
5. End.

We hope the 3 and 4 steps can be merged into the 2 step and automated together.

**Comment by rajeshkio** [comment]
I can take this if there is no urgency to complete this. I can work on it next week.

**Comment by elliotxx** [comment]
@rajeshkio Yeah, this issue is not very urgent, you can start when you are convenient.

**Comment by rajeshkio** [comment]
I am confused. I do not see anything related to the helm chart in the current workflow; the helm chart has a different repo. So does the task include updating the Chart.yml in the helm chart repo?

**Comment by elliotxx** [comment]
@rajeshkio  Ohh, I didn't make it clear. Chart repo is [here](https://github.com/KusionStack/charts/tree/master/charts/karpor). 

The current workflow is as described in the issue, after each release, I manually update the `version` and `appVersion` in the chart repo, similar to this [PR](https://github.com/KusionStack/charts/pull/48/files).

My idea is that after each release, this PR can be automatically generated through a github action ([yaml-update-action](https://github.com/fjogeleit/yaml-update-action?tab=readme-ov-file#advanced-example-with-an-separate-target-repository) is good), and maintainers only need to click `merge`.

Example ( in [release.yaml](https://github.com/KusionStack/karpor/blob/main/.github/workflows/release.yaml#L84) ):
```yaml
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Update current version in the related HelmChart values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          repository: KusionStack/charts
          valueFile: 'charts/karpor/Chart.yaml'
          propertyPath: 'version'
          value: ${{ steps.get_version.outputs.VERSION }}
          branch: bump-karpor-to-${{ steps.get_version.outputs.VERSION }}
          targetBranch: main
          createPR: true
          message: 'refactor: bump karpor version to ${{ steps.get_version.outputs.VERSION }}'
          token: ${{ secrets.GITHUB_TOKEN }}
          workDir: .
```

**Comment by rajeshkio** [comment]
Interesting. This would mean directly updating the version in the helm chart whenever there is a new image without considering if there are any changes in the helm chart repo. Also updating the appVersion in  helm chart means we need to update the helm chart version as well, no?

**Comment by elliotxx** [comment]
@rajeshkio Yeah, as long as release has a new image, we can automatically generate a PR that only includes version bump. And just like you said, `version` (chart version) and `appVersion`(image version) need to be updated. We really need to consider how to update the `version`, its target value is not easy to get.

**Comment by elliotxx** [comment]
@rajeshkio I think of a way, it can obtain and automatically bump chart version:
```yaml
      - name: Get karpor version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Get new chart version
        id: get-chart-version
        run: |
          helm repo add kusionstack https://kusionstack.github.io/charts
          helm repo update
          version=$(helm search repo kusionstack/karpor --versions | head -n 2 | tail -n 1 | awk '{print $2}')
          echo "Current chart version is: $version"
  
          major=$(echo "$version" | cut -d. -f1)
          minor=$(echo "$version" | cut -d. -f2)
          patch=$(echo "$version" | cut -d. -f3)
          new_chart_version="${major}.${minor}.$((patch + 1))"
  
          echo "New chart version is: $new_chart_version"
          echo "::set-output name=new_chart_version::$new_chart_version"
      - name: Bump version in the related HelmChart Chart.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          repository: KusionStack/charts
          valueFile: 'charts/karpor/Chart.yaml'
          propertyPath: '{"version":"${{ steps.get-chart-version.outputs.new_chart_version }}", "appVersion":"${{ steps.get_version.outputs.VERSION }}"}'
          value: ${{ steps.get_version.outputs.VERSION }}
          branch: bump-karpor-to-${{ steps.get_version.outputs.VERSION }}
          targetBranch: main
          createPR: true
          message: 'refactor: bump karpor version to ${{ steps.get_version.outputs.VERSION }}'
          token: ${{ secrets.GITHUB_TOKEN }}
          workDir: .
```
