### ISSUE TITLE
error convert kubeconfig to cluster: failed to parse credential from kubeconfig

### ISSUE THREAD

**Issue by danielstankw** [KusionStack/karpor#553]
### What happened?

I have uploaded the kubeconfig via UI and get the error:
`error convert kubeconfig to cluster: failed to parse credential from kubeconfig`

This is the layout of my config.yaml

```yaml

apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LSXXXXXXXXXXXX==
    server: https://XXXXXXX.gr7.us-east-2.eks.amazonaws.com
  name: XXXXXX
contexts:
- context:
    cluster: XXXXX
    user: XXXXX
  name: XXXXXX
current-context: XXXXXXX
kind: Config
preferences: {}
users:
- name: XXXXXX
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - XXXXX
      - eks
      - get-token
      - --cluster-name
      - XXXXXX
      - --output
      - json
      command: aws
```

Am I missing anything specific in here? 

### What did you expect to happen?

No error

### How can we reproduce it (as minimally and precisely as possible)?

...

### Karpor version

<details>

```console
$ karpor -V
# paste output here
```

</details>
sdadasda

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

**Comment by elliotxx** [comment]
@danielstankw Received, thank you for your feedback! Let's take a look at what's going on. cc @ruquanzhao

**Comment by ruquanzhao** [comment]
Hi, @danielstankw

> ```yaml
> apiVersion: v1
> clusters:
> - cluster:
>     certificate-authority-data: LSXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXCg==
>     server: https://YYYYYYYYYYYYYY.eks.amazonaws.com
> ```

Is this yaml file the entire content of your kubeconfig? 
Normally, there should be `contexts` and `users` part, and your credential will be in `users` part like:
```yaml
 users:
 - name: kwok-demo
   user:
     client-certificate-data: LS0tLSxxxxxxx
```

**Comment by CirillaQL** [comment]
I think this issue is same as my issue https://github.com/KusionStack/karpor/issues/520 , you can see the server ends with eks.amazonaws.com @ruquanzhao @elliotxx

**Comment by danielstankw** [comment]
@ruquanzhao my bad there is also this section, both options do not work

```yaml

apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LSXXXXXXXXXXXX==
    server: https://XXXXXXX.gr7.us-east-2.eks.amazonaws.com
  name: XXXXXX
contexts:
- context:
    cluster: XXXXX
    user: XXXXX
  name: XXXXXX
current-context: XXXXXXX
kind: Config
preferences: {}
users:
- name: XXXXXX
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - XXXXX
      - eks
      - get-token
      - --cluster-name
      - XXXXXX
      - --output
      - json
      command: aws
 
```

**Comment by danielstankw** [comment]
@CirillaQL  can you send me sample of your kubeconfig (annoymized) that worked for you?

**Comment by CirillaQL** [comment]
@danielstankw 
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    server: XXXXXXXXXXXXXXX.eks.amazonaws.com
  name: XXXX-eks22
- cluster:
    certificate-authority-data: LS0tXXXXXXXXXXXXXXXXXXXXXXXXX
    server: https://kubernetes.docker.internal:6443
  name: docker-desktop
contexts:
- context:
    cluster: XXXX-eks22
    user: XXXX-eks22
  name: XXXX-eks22
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
current-context: docker-desktop
kind: Config
preferences: {}
users:
- name: XXXX-eks22
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - XXXXXXX
      - eks
      - get-token
      - --cluster-name
      - XXXX-eks22
      - --output
      - json
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
- name: docker-desktop
  user:
    client-certificate-data: LS0tXXXXXXXXXXXXXXX
    client-key-data: LS0tXXXXXXXXXXXXXXXXXXXXXX
```
This configuration works for me; as you can see, my current context is **docker-desktop**, which is a cluster created by Docker Desktop and runs on my own laptop. However, when I change the current context to **XXXX-eks22**, I get the following error: 'ERROR: error converting kubeconfig to cluster: failed to parse credential from kubeconfig.' As mentioned by a developer in https://github.com/KusionStack/karpor/issues/520, Karpor does not support AWS EKS right now.
