### ISSUE TITLE
Install: Add Helm Variables for LLM API Proxy Settings

### ISSUE THREAD

**Issue by elliotxx** [KusionStack/karpor#736]
## What would you like to be added?
Add proxy configuration parameters in Helm chart to support OpenAI and other LLM API calls in internal network environments.

## Why is this needed?
Many enterprise users deploy Karpor in internal networks where direct internet access is restricted. This feature will:
1. Add new Helm chart parameters:
- httpProxy
- httpsProxy
- noProxy

2. Configure proxy settings for:
- OpenAI API calls
- Other LLM service endpoints

3. Update documentation:
- Add proxy configuration guide
- Include example values

This will make it easier to deploy Karpor in enterprise environments where proxy is required for external API calls.

**Comment by jinjiaKarl** [comment]
Hi, I am interested in contributing to this.

**Comment by jinjiaKarl** [comment]
@elliotxx Hi, thanks for the quick response. 
I am thinking of adding the following parameters. `noProxy` means that the proxy is disabled.

Is it ok to proceed or do you have a better idea? 
```
server:
  ai:
   ......
    proxy:
      # -- Enable proxy settings for AI service connections. When false, proxy settings will be ignored.
      enabled: false
      # -- HTTP proxy URL for AI service connections (e.g., "http://proxy.example.com:8080")
      httpProxy: ""
      # -- HTTPS proxy URL for AI service connections (e.g., "https://proxy.example.com:8080")
      httpsProxy: ""
```

**Comment by elliotxx** [comment]
@jinjiaKarl Hi, I think you’re on the right track with the proxy settings. Just a quick note: `noProxy` isn't about disabling the proxy; it's a list of addresses that should bypass the proxy. Here’s a quick tweak:
```yaml
server:
  ai:
    proxy:
      enabled: true
      httpProxy: "http://proxy.example.com:8080"
      httpsProxy: "https://proxy.example.com:8080"
      noProxy: "localhost,127.0.0.1,example.com"
```
Since the Spring Festival, the reply is later, sorry!
