### ISSUE TITLE
Is there a way to register a cluster declaratively?

### ISSUE THREAD

**Issue by kubebn** [KusionStack/karpor#783]
Hi,

I am wondering if there is any other way to register the cluster except using the UI? Can I somehow apply it via kubectl and Cluster object.

**Comment by elliotxx** [comment]
@kubebn Of course, the cluster registered on the UI will be stored in Karpor's Hub Cluster in the form of CR. You can [export the KubeConfig of the Hub Cluster](https://www.kusionstack.io/karpor/user-guide/how-to-create-token#exporting-the-kubeconfig-for-the-hub-cluster) and then use `kubectl` to manually register the cluster.

**Comment by kubebn** [comment]
> [@kubebn](https://github.com/kubebn) Of course, the cluster registered on the UI will be stored in Karpor's Hub Cluster in the form of CR. You can [export the KubeConfig of the Hub Cluster](https://www.kusionstack.io/karpor/user-guide/how-to-create-token#exporting-the-kubeconfig-for-the-hub-cluster) and then use `kubectl` to manually register the cluster.

However, is there a way to prepare a CR without registering it in UI? Let's say if I am planning to spin up 100 clusters and I do not want to register them one by one in the UI, I just want them to be added to karpor via GitOps.

**Comment by elliotxx** [comment]
@kubebn  This requirement is reasonable and the `GitOps` idea is cool. 
Under the current karpor situation, you can quickly register or delete clusters through GitOps. 
1. Manually construct the [Cluster CR](https://github.com/KusionStack/karpor/blob/main/pkg/kubernetes/apis/cluster/types.go#L36) of each cluster, including `endpoint`, `caBundle`, `credential` etc
2. Store them in Git Repo
3. Configure the GitRepo connection in Argo or Flux and [Karpor Hub Cluster's KubeConfig](https://www.kusionstack.io/karpor/user-guide/how-to-create-token#exporting-the-kubeconfig-for-the-hub-cluster).

In this way, just add or delete Cluster CR in GitRepo to quickly manage the clusters in Karpor.

**PS**: If you need it, we can write a `terraform provider` for cluster registration that can be more easily integrated into any Gitops process

---

The following is a Demo video of using `kubectl` to operate `cluster CR`. You can refer to it.

https://github.com/user-attachments/assets/d2314be8-6c8b-4af6-947e-d04c0383dcc1

---

A example for Cluster CR:
```yaml
apiVersion: cluster.karpor.io/v1beta1
kind: Cluster
metadata:
  name: demo-cluster
spec:
  access:
    caBundle: [YOUR_CABUNDLE]
    credential:
      type: X509Certificate
      x509:
        certificate: [YOUR_CERTIFICATE]
        privateKey: [YOUR_PRIVATEKEY]
    endpoint: https://[YOUR_CLUSTER_ENDPOINT_HOST]:[YOUR_CLUSTER_ENDPOINT_PORT]
  description: ""
  displayName: Demo Cluster
```
