### ISSUE TITLE
Karpor behind ingress getting error recv() failed (104: Connection reset by peer) while reading upstream

### ISSUE THREAD

**Issue by vickydev90** [KusionStack/karpor#801]
Hi,

I am trying to run karpor ui behind ingress but on hitting endpoint i get  error "104: Connection reset by peer)".
Has anyone tried running karpor behind ingress?

here is my configuration 

```
Karpor version - v0.6.1
```
ingress config - 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-connect-timeout: 600s
    nginx.ingress.kubernetes.io/proxy-read-timeout: 600s
    nginx.ingress.kubernetes.io/proxy-send-timeout: 600s
    nginx.ingress.kubernetes.io/server-snippet: keepalive_timeout 120s;
  name: karpor-ingress
  namespace: karpor
spec:
  rules:
  - host: karpor.xyz.net
    http:
      paths:
      - backend:
          service:
            name: karpor-server
            port:
              number: 7443
        path: /
        pathType: Prefix
```

i have tried proxy read annotation but didn't work for me.
Appreciate any leads.
