### ISSUE TITLE
Token Based Cluster Context Not Working

### ISSUE THREAD

**Issue by kmadel** [KusionStack/karpor#819]
### What happened?

Uploading the following Kube Config results in this error:
```
E0315 13:56:23.962506       1 authentication.go:63] "Unable to authenticate the request" err="verifying certificate SN=4792605077399134197, SKID=, AKID=9B:3D:E7:D3:5D:64:7F:70:81:AF:C8:F0:6D:BA:CA:CB:AF:24:B0:D2 failed: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"kubernetes\")"
```

Config yaml:
```
apiVersion: v1
kind: Config
clusters:
- cluster:
    server: https://xxxxxxxxxxxx/kubernetes/project/demos/virtualcluster/xxxx
    insecure-skip-tls-verify: true
  name: loft
contexts:
- context:
    cluster: loft
    user: loft
    
  name: loft
current-context: loft
users:
- name: loft
  user:
    token: K*************************************************7
```

### What did you expect to happen?

Based on this merged PR, I would expect it to work with just a user.token: https://github.com/KusionStack/karpor/pull/527

### How can we reproduce it (as minimally and precisely as possible)?

Install vCluster Platform: https://www.vcluster.com/docs/platform/install/quick-start-guide
Then [create a vCluster](https://www.vcluster.com/docs/platform/use-platform/virtual-clusters/create/create-no-template) with the Platform, [export the KubeConfig](https://www.vcluster.com/docs/platform/use-platform/virtual-clusters/retrieve-kube-config) and add it to Karpor.

### Karpor version

kusionstack/karpor:v0.6.3

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>
